### PR TITLE
ArcPlot node_position fix

### PR DESCRIPTION
**Pull request by Rabeez**
There were a couple of issues with PR #543 
- Due to some radii being bigger than 1, the bigger nodes were clipped by the bottom edge of the plot.
- Similarly the rightmost nodes were being clipped off.

Screenshot of problem 2:
image

After fix:
image

- @ericmjl

### CODE REVIEW

**Comment by Rabeez** [comment]
@ericmjl for the test images in `result_images/test_plots` do I replace the image with the new plot if a test is failing? 
Also where is the random seed being set for the 'test_plots.py' file?  Since the plot used for comparison (the `erdos_renyi_graph`) is random.

**Comment by ericmjl** [comment]
Oh my, I'm so, so sorry, @Rabeez, for dropping the ball here. I must have opened the PR while at work, and then had to go back to my work context.

If it's not too late to pick up on the PR again, to answer your questions:

> for the test images in result_images/test_plots do I replace the image with the new plot if a test is failing?

Yes, please go ahead and replace the image!

> Also where is the random seed being set for the 'test_plots.py' file?

I haven't setting random seeds, but I do recognize that this is good practice. Would you be kind enough to add it to the PR?

**Comment by Rabeez** [comment]
@ericmjl I've fixed the stuff that was missing from the PR. I also went ahead and made tests for the features I added (edge color and node size). 
The problem with Travis is still here. The build fails and I'm not sure what the error is about.

**Comment by ericmjl** [comment]
@Rabeez let's not worry about Travis for a while. I have admittedly neglected nxviz infrastructure for a bit because of work occupying most of my time.

Can you paste the output of pytest here? Checking that it works on your computer is at least better than nothing :smile:.

**Comment by Rabeez** [comment]
Output for `py.test`. 
```
====================================== test session starts ======================================
platform win32 -- Python 3.6.7, pytest-5.2.0, py-1.8.0, pluggy-0.12.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\Users\\Rabeez Riaz\\Documents\\Programming\\Python programs\\nxviz\\.hypothesis\\examples')
rootdir: C:\Users\Rabeez Riaz\Documents\Programming\Python programs\nxviz
plugins: hypothesis-4.37.0, cov-2.7.1
collected 38 items

tests\test_geometry.py ....                                                                [ 10%]
tests\test_io.py .....                                                                     [ 23%]
tests\test_nxviz.py ........                                                               [ 44%]
tests\test_plots.py ........                                                               [ 65%]
tests\test_polcart.py ......                                                               [ 81%]
tests\test_utils.py .......                                                                [100%]

======================================= warnings summary ========================================
C:\Users\Rabeez Riaz\.conda\envs\nxviz\lib\site-packages\win32\lib\pywintypes.py:2
  C:\Users\Rabeez Riaz\.conda\envs\nxviz\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os

tests/test_plots.py::test_matrix_plot
  C:\Users\Rabeez Riaz\.conda\envs\nxviz\lib\site-packages\numpy\matrixlib\defmatrix.py:71: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)

tests/test_plots.py::test_edge_color
tests/test_plots.py::test_node_size
  C:\Users\Rabeez Riaz\Documents\Programming\Python programs\nxviz\nxviz\plots.py:181: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
    self.figure = plt.figure(figsize=figsize)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================ 38 passed, 4 warnings in 6.43s =================================
```

**Comment by ericmjl** [comment]
Thanks @Rabeez! 

By the way, would you like to join in and become a maintainer for the project? Please let me know here, happy to give you commit rights to the repository as well.

**Comment by Rabeez** [comment]
What would be my responsibilities? If it's just keeping up with issues and PRs I can do that during slow days at work without much issue.

**Comment by ericmjl** [comment]
> If it's just keeping up with issues and PRs

Exactly that! It's also what I'm doing :smile:.

**Comment by ericmjl** [comment]
I'll add you in, and you can feel free to decide :smile:.

**Comment by Rabeez** [comment]
Sure, I think I can handle that 😄 Thanks

**Pull request merged**
