### PR TITLE
Add node label layout

### PR DESCRIPTION
**Pull request by AlirezaTheH**
Hi @ericmjl, this PR adds node label layout feature discussed in #674.
Currently it adds `"node_center"`,`"standard"`, `"numbers"` and `"rotate"` for `circos` node labels, But I think we can add `"standard"`layout for `arc` and `matrix` labels too.

Here is some examples for `"numbers"` and `"rotate"` layouts.

image
image

Detailed examples also updated in examples directory and tests has been added.

### CODE REVIEW

**Comment by AlirezaTheH** [comment]
Hi @ericmjl ✋
`"standard"` layout has been added for `arc` and `matrix` plots, tests and examples included.

image
image

**Comment by ericmjl** [comment]
Wow! Impressive stuff, @AlirezaTheH! Can you do one final thing for me, please? In the examples that you've newly created, could you temporarily add a comment at the top of the file that this was created by you? 

I plan to move the examples into the docs, and with that, I'd like to make sure your effort in creating the examples is fully recognized!

**Comment by ericmjl** [comment]
Also, once you're done, please let me know. (I nearly hit the Big Green Button a day ago, thankfully that didn't happen!) I'm ready to hit merge :smile:

**Comment by AlirezaTheH** [comment]
> I plan to move the examples into the docs, and with that, I'd like to make sure your effort in creating the examples is fully recognized!

I'd be appreciate it, thank you!

**Comment by ericmjl** [comment]
Alrighty, I'm going to hit the merge button!

**Pull request merged**
