### PR TITLE
Updated usage page of docs

### PR DESCRIPTION
**Pull request by fding253**
This PR resolves issue #570.

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# PR Description

Added basic details of MatrixPlot and ArcPlot to "Usage" page of docs. Let me know if you'd like me to make any further edits!

# Relevant Reviewers

- @ericmjl

### CODE REVIEW

**Comment by Rabeez** [comment]
Thanks @fding253 , do you think it will be useful to have a link to the examples directory on this page? Since it has usage examples of more detailed versions of the plots.

**Comment by ericmjl** [comment]
@fding253 thanks for  the PR! I very much appreciate it :smile:. Before we merge, can I ask you to send me a screenshot of the rendered docs? This way I know the docs will build correctly on readthedocs. (I wish there was a good way of automatically testing this!)

**Comment by fding253** [comment]
Sure! I added a link to the API docs as well as the examples directory at the bottom. 

Here are some screenshots:
image
image
image
image

**Comment by Rabeez** [comment]
@ericmjl I think the Travis configuration has some issues (which I don't know how to fix) but this PR hasn't changed any code files so is it okay to merge?

**Comment by ericmjl** [comment]
@Rabeez yes, I'm going to hit merge. Thanks for helping out with the review. Also, many apologies to @fding253, I dropped the ball on this PR. You did a wonderful job with generating the example images!

**Comment by ericmjl** [comment]
To clarify, I hit merge even though the PR was failing tests because I had fixed the Travis build system in another PR.

**Pull request merged**
